apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: profile-service

  template:
    metadata:
      labels:
        app: profile-service

    spec:
      containers:
        - name: profile-service
          image: profile-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 3002

          envFrom:
            - configMapRef:
                name: profile-service-config
            - secretRef:
                name: app-secrets